# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 12) do

  create_table "events", :force => true do |t|
  end

  create_table "memberships", :force => true do |t|
    t.column "person_id",  :integer
    t.column "place_id",   :integer
    t.column "role",       :string
    t.column "home",       :boolean
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "open_id_authentication_associations", :force => true do |t|
    t.column "server_url", :binary
    t.column "handle",     :string
    t.column "secret",     :binary
    t.column "issued",     :integer
    t.column "lifetime",   :integer
    t.column "assoc_type", :string
  end

  create_table "open_id_authentication_nonces", :force => true do |t|
    t.column "nonce",   :string
    t.column "created", :integer
  end

  create_table "open_id_authentication_settings", :force => true do |t|
    t.column "setting", :string
    t.column "value",   :binary
  end

  create_table "people", :force => true do |t|
    t.column "login",                     :string
    t.column "given_name",                :string
    t.column "family_name",               :string
    t.column "org",                       :string
    t.column "street_address",            :string
    t.column "locality",                  :string
    t.column "region",                    :string
    t.column "postal_code",               :string
    t.column "country_name",              :string
    t.column "tel",                       :string
    t.column "email",                     :string
    t.column "url",                       :string
    t.column "photo",                     :string
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "openid_url",                :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "identity_url",              :string
    t.column "nickname",                  :string
  end

  create_table "places", :force => true do |t|
    t.column "org",            :string
    t.column "street_address", :string
    t.column "locality",       :string
    t.column "region",         :string
    t.column "postal_code",    :string
    t.column "country_name",   :string
    t.column "tel",            :string
    t.column "email",          :string
    t.column "url",            :string
    t.column "photo",          :string
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "lat",            :string
    t.column "lng",            :string
  end

end
